version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: dispander
    versions:
    - 0.4.1
  - dependency-name: daug
    versions:
    - 2021.4.5.1
    - 2021.4.6.1
